server:
  port: 8989
  servlet:
    context-path: /api

spring:
  application:
    name: transactionstatistics

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

logging:
  file:
    name: logs/application.log